//
// Created by maria on 08.10.18.
//

#ifndef MINI_FS_FS_CONSTANTS_H
#define MINI_FS_FS_CONSTANTS_H

#define INODES_PER_BLOCK 8
#define POINTERS_PER_INODE 4
#define POINTERS_PER_BLOCK 256
#define FILENAME_LENGTH 12
#define INODES_NUM_IN_DIRECTORY 6
#define SIZE_OF_BLOCK 2048
#define TOTAL_NUM_OF_BLOCKS 136
#define NUM_BLOCKS_FOR_INODES 8


#endif //MINI_FS_FS_CONSTANTS_H
